# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "centos7vm0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "centos7vm0#{i}.test.com"
      node.vm.network "private_network", ip: "192.168.1.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "centos7vm0#{i}"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

end
